engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.php"

exclude_paths:
- "**.min.js"
- "includes/class-freemius-abstract.php"
